### ISSUE TITLE
Add import scala.language.higherKinds to generated code 

### ISSUE THREAD

**Issue by elbiczel** [twitter/scrooge#121]
In scala 2.10.3 when scalac -Xlint option is enabled a warning is generated that generated sources use higherKinds: http://www.scala-lang.org/api/2.10.3/index.html#scala.language$@higherKinds:languageFeature.higherKinds . It would be good to add ``` import scala.language.higherKinds ``` to the generated source code, so that one does not need to include ```-language:higherKinds``` scalac option on the whole project.

**Comment by mosesn** [comment]
We have since fixed this.
