### ISSUE TITLE
Support closing underlying service

### ISSUE THREAD

**Issue by sslavic** [twitter/scrooge#125]
Please add support for closing underlying service when closing server, and when closing client.
For more details see [this](https://groups.google.com/d/msg/finaglers/OxAOu-iPVI0/Bd7CfDRhlDEJ) discussion at finaglers mailing list.

**Comment by mosesn** [comment]
This issue came up again on finagle: https://github.com/twitter/finagle/issues/572

**Comment by yufangong** [comment]
closing underlying service has been merged in 1fa4f0c6df334b1bcca71fe53683ee15f4aa5cc5. Thank you!
