### ISSUE TITLE
Scala 2.11 support

### ISSUE THREAD

**Issue by arboreal84** [twitter/scrooge#129]
2.11 is the new stable version of the Scala language.
When will Scrooge support Scala 2.11?

**Comment by adriancole** [comment]
Looks like we have an candidate fix https://github.com/twitter/scrooge/pull/198

Can someone see if this is ok to merge? This is blocking zipkin for example, who want to support scala 2.11

**Comment by mosesn** [comment]
scrooge supports 2.11 successfully now!
