### ISSUE TITLE
Add support for Tree/Recursive structs

### ISSUE THREAD

**Issue by zfy0701** [twitter/scrooge#160]
which has already been included in thrift 0.9.2:
https://issues.apache.org/jira/browse/THRIFT-2421

**Comment by pavanch007** [comment]
Is anyone working on this scrooge feature?

**Comment by kevinoliver** [comment]
@pavanch007 nobody here at twitter is working on it as far as i know.

**Comment by pavanch007** [comment]
Thanks.. good to know. I will take this on.. do you have any pointers to start with this task?

**Comment by kevinoliver** [comment]
@pavanch007 nice! i haven't spent any time thinking about this one so i don't have much in the way of advice.

best i can do is tell you what i'd do. i'd start by adding a recursive struct and service using that struct to a test idl in scrooge-generator. then see what blows up when you run the tests. once the parser and generator is not blowing up, i'd update a test case to use the recursive struct and verify the behavior.

we can try to work through this with you as you go forward.

**Comment by fkorotkov** [comment]
@pavanch007, have you made any progress? Just curious :-)

**Comment by pavanch007** [comment]
@fkorotkov Sorry for not circling back. This got de-prioritized and I'm not actively working on this.

**Comment by mosesn** [comment]
This issue is related to https://github.com/twitter/scrooge/issues/85

**Comment by taylorleese** [comment]
I believe this was closed in error so reopening.

**Comment by mosesn** [comment]
This was fixed in #244 🎆

**Comment by ihorkhavkin** [comment]
@mosesn is it a mistake to resolve this issue? see "This change doesn't yet support recursive types which is needed to fully resolve #160." on #244

**Comment by mosesn** [comment]
@ihorkhavkin maybe!  what's the distinction between self-referential types and recursive types?

**Comment by zfy0701** [comment]
recursive:
```
struct A {
  1 B b;
}

struct B {
  1 A a;
}
```
self referential
struct A {
  1 A a;
}

**Comment by mosesn** [comment]
@zfy0701 got it, thanks!

**Comment by folex** [comment]
Please do!

**Comment by mosesn** [comment]
This was fixed by @folone here: https://github.com/twitter/scrooge/commit/2a731bbc49cdf11372cd1d001b9446451dcd84fe

**Comment by folone** [comment]
Nice, thanks for pushing this @mosesn!
