### ISSUE TITLE
Generated code from scrooge is incompatible with thrift if a service method returns an enum

### ISSUE THREAD

**Issue by steveniemitz** [twitter/scrooge#165]
Given an example thrift file:

```
enum ResultCode
{
  OK,
  TRY_LATER
}

service test
{
  ResultCode test();
}
```

Thrift will generate this code as part of the codec:
```
switch (schemeField.id) {
  case 0: // SUCCESS
    if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
      struct.success = ResultCode.findByValue(iprot.readI32());
      struct.setSuccessIsSet(true);
    } else { 
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
    }
    break;
  default:
    org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
}
```

Where as scrooge will generate this:
```
switch (_field.id) {
  case 0: /* success */
    switch (_field.type) {
      case TType.ENUM:
        ResultCode success_item;
        success_item = ResultCode.findByValue(_iprot.readI32());
        success = success_item;
        break;
      default:
        TProtocolUtil.skip(_iprot, _field.type);
    }
    builder.success(success);
    break;
  default:
    TProtocolUtil.skip(_iprot, _field.type);
}
```

Note the main difference here is that scrooge is expecting an ENUM type, where thrift is expecting an i32.  The format on the wire is in fact encoded as an i32 coming from a thrift service.  The net result is that all calls return null instead of the actual value returned to the service.

**Comment by nshkrob** [comment]
I assume you use --language=java? Scrooge 3.17.0 generates different output for me:

$ java -jar $jar -l java issue-165.thrift --verbose
$ cat thrift/test.java
...
      switch (field.id) {
        case 0: // SUCCESS
          if (field.type == TType.I32) {
            this.success = ResultCode.findByValue(iprot.readI32());
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
...

Please test with the latest scrooge. 

See also https://github.com/twitter/scrooge/commit/98ba444697f5c6209471fcee7066b7bdb10a297a - scrooge should accept both I32 and Enum types from the wire.

**Comment by steveniemitz** [comment]
We're building with language=experimental-java, also on 3.17.0.

**Comment by nshkrob** [comment]
I see, now I can reproduce this - reopening. experimental-java isn't as widely used by us, but patches are welcome to fix this.

**Comment by mosesn** [comment]
We deleted experimental-java because it mostly did not work.
