### ISSUE TITLE
Add instance of `LabelledGeneric` to Scrooge structs (under a flag)

### ISSUE THREAD

**Issue by jedesah** [twitter/scrooge#170]
I am trying to get rid of a fork of Scrooge that we have at Whitepages. This is the last step to get rid of it. The main reason for our fork right now is to supply Json Codecs for Scrooge Structs (because previously we were reflecting over Scrooge structs (before I got here) and that turned out to be a horrendous idea as you can expect, for multiple reason). I never bothered asking if we could merge this codec generation because I didn't figure it was appropriate for Scrooge to merge our codecs for a specific json library even under a flag.

I just finished prototyping an idea where Scrooge could generate an instance of `LabelledGeneric` (from shapeless). This would be sufficient for us to derive our json codecs. Of course, it would be under a flag, and I think it is sufficiently generic to be useful to a large audience. `LabelledGeneric` allows one to derive instances for arbitrary typeclasses. It also means that clients that activate this flag will be able to use Shapeless lenses to work with the structs (I think, I will confirm this).

Here is a stackoverflow question where I asked for help on the matter and @travisbrown  was nice enough to jump in and help out: http://stackoverflow.com/questions/28119757/in-shapeless-can-i-supply-an-instance-of-labelledgeneric-for-non-case-classes

So before spending too much time on this, I would like to know that there is a good chance that a PR on my part for this will get merged.

**Comment by mosesn** [comment]
@jedesah this is over a year old, so I have no idea if you're still using scrooge.  For what it's worth, I think adding a dependency on shapeless would be a hard sell.  Do you know if there's another way we could solve this problem?

**Comment by jedesah** [comment]
@mosesn I am not sure there is another way of solving this problem asides from making the scala code that represents structs more "case class like". I no longer work at Whitepages. Pinging @pkohan so that he can attest as to whether or not Whitepages cares to make such a change.

**Comment by triggerNZ** [comment]
https://github.com/travisbrown/scrooge-circe-demo/blob/master/src/main/scala/demo/package.scala provides generic instances for scrooge-generated thrifts

**Comment by mosesn** [comment]
@pkohan it sounds like scrooge-circe might have solved your problem?  I'm going to close this ticket, but please feel free to reopen if you'd like to revisit it.
