### ISSUE TITLE
unapply method should return Option[TupleN] not Option[ProductN]

### ISSUE THREAD

**Issue by jstultz** [twitter/scrooge#171]
Perhaps there is a reason for this that I'm unaware of, but the generated unapply method for thrift structs returns a Product rather than a Tuple. Is there a reason why this is preferred? Behavior for case classes in scala is to return a Tuple, and this is more flexible as it will work with code that expects either.

I ran into this issue when using a generated class in a slick projection, which works very nicely with case classes that provide `tupled` and `unapply` methods where `unapply` returns a tuple: http://slick.typesafe.com/doc/2.0.0/schemas.html#mapped-tables

If the `User` class in that example were scrooge-generated, rather than a case class, it would need to be:

``` scala
  def * = (id.?, first, last) <> ((User.apply _).tupled, fromUser)
```

Where `fromUser` would need to be defined as a function that returns a tuple, since that's not already provided.

**Comment by sagemintblue** [comment]
Or how about making the internal `Immutable` class a case class, which would give us an alternative `unapply`?

I'd like to take advantage of implicits available for `TupleN` types, which are generally not available for `ProductN` types, for instance those within `scala.math.Ordering` and `com.twitter.algebird.Semigroup` /cc @johnynek

**Comment by mosesn** [comment]
No idea why this is, maybe historical reasons?  I'd be happy to see a PR fixing this.

**Comment by jstultz** [comment]
It took me a while to get around to it, but here's a stab at it:

https://github.com/twitter/scrooge/pull/248

**Comment by kevinoliver** [comment]
This got merged in https://github.com/twitter/scrooge/commit/dc119779ede0e80153068fff02642c9e0afcb038
