### ISSUE TITLE
Scrooge generator cannot parse files with // comments not on their own line

### ISSUE THREAD

**Issue by vsabella** [twitter/scrooge#174]
We noticed that // comments inline with thrift structs will break scrooge parsing. The standalone thrift compiler doesn't mind these.

````thrift
struct Foo
{
    1: optional string bar // this comment will break scrooge parsing
}
````

**Comment by mosesn** [comment]
We can do this now!  See here in this test: https://github.com/twitter/scrooge/blob/develop/scrooge-generator-tests/src/test/thrift/standalone/naughty.thrift#L16
