### ISSUE TITLE
Building Scrooge Error

### ISSUE THREAD

**Issue by qiyang0221** [twitter/scrooge#177]
when run ./sbt +publish-local,
I got an error 
(scrooge-runtime/*:update) sbt.ResolveException: unresolved dependency: org.apache.thrift#libthrift;0.5.0: not found
Should I change any ivy files or pom files?where to change?

**Comment by nshkrob** [comment]
Scrooge uses http://maven.twttr.com/ to resolve libthrift/0.5.0-1:
https://github.com/twitter/scrooge/blob/master/project/Build.scala#L97

Make sure you can reach that server.

**Comment by qiyang0221** [comment]
Yes, I can reach http://maven.twttr.com/ by chrome, it tell me it works.
Is there any problem with my environment?

**Comment by qiyang0221** [comment]
ping maven.twttr.com timeout. Is there any other repo to replace maven.twttr.com

**Comment by nshkrob** [comment]
This looks like a network issue on your side. 
Note that you only need to download the jars once, and then maven should cache it locally for later builds. If you can reach that server intermittently, you can try until it works, or use some kind of a proxy to reach it.

**Comment by iwataka** [comment]
I got the same error and solved it by adding `resolvers += "twitter-repo" at "https://maven.twttr.com"` to `project/plugins.sbt`.
I hope this can help you.

**Comment by ryanoneill** [comment]
Closing this issue as it appears to be a problem with reaching maven.twttr.com.
