### ISSUE TITLE
Unable to parse configuration com.twitter:scrooge-maven-plugin:3.18.0:compile for parameter localRepository

### ISSUE THREAD

**Issue by maasg** [twitter/scrooge#185]
After having to update to version 3.18.0 due to the issue with 3.17.0 described on #184 , I'm hitting the wall with this error:
```
Failed to execute goal com.twitter:scrooge-maven-plugin:3.18.0:compile (thrift-sources) on project service-finagle:
Unable to parse configuration of mojo com.twitter:scrooge-maven-plugin:3.18.0:compile for parameter localRepository: Cannot create instance of interface org.apache.maven.artifact.repository.ArtifactRepository
``` 
I checked the code [here](https://github.com/twitter/scrooge/blob/scrooge-3.18.0/scrooge-maven-plugin/src/main/java/com/twitter/AbstractMavenScroogeMojo.java#L181)  and that property has a default value if not provided.

No matter what I do, not add it or provide it like this:
```xml
<configuration>
    <localRepository>/path/to/local/.m2</localRepository>
    <thriftOpts>
    <!-- add other Scrooge command line options using thriftOpts -->
        <thriftOpt>--finagle</thriftOpt>
   </thriftOpts>
   <!-- tell scrooge to extract thrifts from these artifacts -->
   <buildExtractedThrift>true</buildExtractedThrift>
   <checkStaleness>false</checkStaleness>
</configuration>
``` 
I get the same error.  After hours hitting the wall for a simple build, I'm getting insane. Any ideas?

**Comment by maasg** [comment]
I see that this part of the code has been recently introduced with: https://github.com/twitter/scrooge/commit/08929dd5dc5549f816f552360da41a3d7b8f53d0

**Comment by nshkrob** [comment]
We are working on fixing this, thanks for reporting.

**Comment by nshkrob** [comment]
This has been fixed. Please upgrade to scrooge-maven-plugin 3.18.1.

**Comment by maasg** [comment]
Thanks for the quick solution!
