### ISSUE TITLE
Scrooge 3.18.1 not release for Scala 2.11

### ISSUE THREAD

**Issue by vsabella** [twitter/scrooge#186]
Scrooge 3.18.1 was not released for Scala 2.11 on Maven Central, is that by design?

**Comment by mosesn** [comment]
@vsabella I ran into trouble with mustache, where it wasn't easy for us to upgrade to a newer version of mustache that supported 2.11.  I don't remember the specifics, but we'd be happy to look into it again if you make a PR.

**Comment by csaltos** [comment]
FYI I've just opened this post on mustache group -> https://groups.google.com/forum/#!topic/mustachejava/8acnzuaoAG8

**Comment by csaltos** [comment]
Dear @mosesn in the meantime I've made this PR -> https://github.com/twitter/scrooge/pull/193

**Comment by csaltos** [comment]
TravisCI is missing finagle and util dependencies on PR https://github.com/twitter/scrooge/pull/193, so I'm creating a new PR trying to correct this.

**Comment by csaltos** [comment]
OK, ready !! ... At the PR https://github.com/twitter/scrooge/pull/194 the build should be fixed for TravisCI and a ready Scala 2.10/Scala 2.11 cross versioned build (I hope).

**Comment by csaltos** [comment]
FYI I create this issue at mustache -> https://github.com/spullara/mustache.java/issues/146

**Comment by viktortnk** [comment]
Considering (JDK 7 support for Finagle and associated projects) https://groups.google.com/forum/#!topic/finaglers/wkB9hDeLrSo

Am I right to think that it won't be an issue after 1st of August?

**Comment by mosesn** [comment]
We have support for 2.11 now!

**Comment by csaltos** [comment]
Great !!
