### ISSUE TITLE
Supporting `withFoo(newValue)` methods

### ISSUE THREAD

**Issue by AndreiBarsan** [twitter/scrooge#192]
One of the biggest differences between accessing regular Thrift structs and Scrooge structs in Scala is that the latter are immutable. That is, if one wishes to "modify" a Scrooge Thrift, one must manually create a copy of it with all fields identical, with the exception of the one(s) we want to modify, which can be a bit tedious.

To facilitate this workflow, a possible solution would be to add a set of new generated methods designed to return an updated copy of the struct on which they are invoked.

For instance, `student.withFirstName("Joey")` could return a copy of `student` with the name set to "Joey".

Would such an addition fit Scrooge, or would it clash with its philosophy?

**Comment by nshkrob** [comment]
Scrooge-generated structs have a copy method that does this:

student.copy(firstName = "asdf")
