### ISSUE TITLE
Document libthrift 0.5 vs. 0.9.1 decision/compatibility/options

### ISSUE THREAD

**Issue by stephenh** [twitter/scrooge#197]
Hi,

After several years of running an ancient/trunk/pre-release build of libthrift, we finally went through the process of moving to libthrift 0.9.1 (with the canonical thrift codegen output) ~a year or so ago.

Today I was hoping to do a spike with Scrooge, but I noticed the libthrift 0.5.0-1 version. I understand if internally you're still on libthrift 0.5.0-ish, and so don't want to/can't run libthrift.

I assume you've probably studied the problem a bit; so, it's admittedly selfish, but could you add a page to the Scrooge docs about Thrift versions? E.g. the rationale of why you're still on libthrift 0.5.0-1, and if users that did want to use libthrift 0.9.1+ could do so either by a) forking Scrooge, b) overriding the libthrift version at runtime and using 0.9.1 anyway, c) something else...

And maybe if the are/are not breaking changes between libthrift 0.5.0-1 that Scrooge would use and libthrift 0.9.1 that clients might use, in terms of wire/binary protocol and/or libthrift API.

(I was not directly part of our effort to move to 0.9.1, so apologies if these are naive questions that I should just know. ...my recollection is that wire protocol didn't change, but the libthrift Java API did ... or the codegen output did...)

Apologies if this is already spelled out somewhere; I attempted to search the docs/open issues/etc. Thanks!

**Comment by nshkrob** [comment]
Hi @stephenh, we still use libthrift 0.5.0 because upgrading would require some work to upgrade internal users at Twitter. We do plan to upgrade to 0.9.x eventually (we don't have a date for that though).

The two libthrift versions are wire-compatible, and the API changes are small. Depending on what other dependencies you have, either of your options a) and b) would work. I.e. you might be able to just use scrooge-generated files with libthrift 0.9.x with minimal or no changes.

**Comment by stephenh** [comment]
Hi Nik,

Thanks for the response; I'll try forcing the runtime version to libthrift 0.9.1 as a first step and see what happens.

**Comment by stephenh** [comment]
I did some quick spikes with forcing libthrift 0.9.1 at runtime and everything seems fine so far. Whew! :-)

I'll have to do some more vetting, and not sure if we'll end up using this widely/in production, but so far so good. 

Thanks for the clarifications!
