### ISSUE TITLE
Guard use of BinaryProtocol.setReadLength

### ISSUE THREAD

**Issue by adriancole** [twitter/scrooge#203]
Via 018aef8c27d22ab3b8a7fb1c798ee767099ecb6d, scrooge started using `TBinaryProtocol.setReadLength` about 2 weeks ago.

This pins the maximum libthrift version to 0.9.0 as `TBinaryProtocol.setReadLength` was removed starting in 0.9.1. 
https://github.com/apache/thrift/commit/2ca9c2028593782621c8876817d8772aa5f46ac7

Can this be implemented in a way that's compatible with versions beyond 0.9.0? Here's an example https://issues.apache.org/jira/browse/PARQUET-180

**Comment by kevinoliver** [comment]
that seems like a reasonable way to patch it.

**Comment by adriancole** [comment]
ok I'll give a try at patching this.

**Comment by adriancole** [comment]
started to look at patching, but the project setup seemed far more effort than the actual change. ducking in hopes someone else can do it that already has scrooge and its various dependencies staged.

**Comment by yufangong** [comment]
Thanks, @adriancole. We have removed `TBinaryProtocol.setReadLength` usage in 997f2464ca04998ce5b7a73c56c7667d1754a01b. Closing this issue for now.
