### ISSUE TITLE
Generate type alias from the scrooge-sbt-plugin

### ISSUE THREAD

**Issue by reikje** [twitter/scrooge#206]
When working in a client class, which uses a bunch of thrift services, it would be nice to have type aliases generated. Currently I do this manually:

	import my.package.FooService.{FutureIface => FooFutureIface}
	import my.package.BarService.{FutureIface => BarFutureIface}
	import my.package.DoeService.{FutureIface => DoeFutureIface}

instead of using `FutureIface` directly - I program against the aliases which improves readability in my code. I wonder if there instead was a way to auto-generate a type alias from the `scrooge:gen` task.

**Comment by nshkrob** [comment]
You could use FooService[Future] instead of the FutureIface. Another option is to import FooService and use FooService.FutureIface.
In general, we want to minimize what Scrooge generates, and in this case I think there are simpler alternatives.

**Comment by reikje** [comment]
Thanks, i'll look into using `FooService[Future]` from now on.
