### ISSUE TITLE
"compile" function in ScroogeSBT conflicts with sbt.Keys.compile

### ISSUE THREAD

**Issue by matthandlersux** [twitter/scrooge#209]
adding the scrooge sbt plugin causes sbt to import all of it's keys into the namespace of a `built.sbt` file. so in `build.sbt`, the top of the file magically receives:

```scala
import _root_.com.twitter.scrooge.ScroogeSBT._
import Keys._
```
this includes the `compile` function here: https://github.com/twitter/scrooge/blob/develop/scrooge-sbt-plugin/src/main/scala/com/twitter/ScroogeSBT.scala#L13 , but it collides with https://github.com/sbt/sbt/blob/1.0.x/main/src/main/scala/sbt/Keys.scala#L188

this becomes a problem when you want to have target specific settings, for example:

```scala
// in build.sbt
wartremoverErrors in (Compile, compile) ++= Seq(...)

// compile error:
//
// .../build.sbt:43: error: reference to compile is ambiguous;
// it is imported twice in the same scope by
// import _root_.com.twitter.scrooge.ScroogeSBT._
// and import Keys._
//  wartremoverErrors in (Compile, compile) ++= Seq(...)
```
as a temporary workaround, you can do:

```scala
// at the top of build.sbt
import Keys.{compile => sbtCompile}
...
wartremoverErrors in (Compile, sbtCompile) ++= Seq(...)
```
renaming the function in scrooge should fix it.

**Comment by mosesn** [comment]
Sweet, you mind making a PR?

**Comment by matthandlersux** [comment]
@mosesn yup, should have some time this weekend

**Comment by mosesn** [comment]
This was fixed here: https://github.com/twitter/scrooge/pull/210.  Thanks @matthandlersux !
