### ISSUE TITLE
scrooge sbt plugin 2.11 support and location?

### ISSUE THREAD

**Issue by drozzy** [twitter/scrooge#212]
While scrooge-core is available for Scala 2.11, `scrooge-sbt-plugin` requires Scala 2.10

Also, in the docs (https://twitter.github.io/scrooge/SBTPlugin.html), plugin version "3.18.1" is indicated, yet I can't find that version in the repo:
https://oss.sonatype.org/content/groups/public/

Am I looking in the wrong place?

**Comment by vkostyukov** [comment]
Hey @drozzy,

`scrooge-sbt-pluing` is published to [Bintray]( https://bintray.com/twittercsl/sbt-plugins/scrooge-sbt-plugin/) while the rest of the Scrooge goes to MC. Looks like 3.18.1 is [there](https://bintray.com/twittercsl/sbt-plugins/scrooge-sbt-plugin/3.18.1/view).

**Comment by travisbrown** [comment]
@drozzy For the record, SBT plugins must have the same Scala version as the version of SBT a project uses, which for SBT 0.13 is 2.10. In general SBT plugins do not need to be published for every version that a project is cross-built against (e.g. a Scala 2.11 version of the Scrooge SBT plugin would be useless, since there's no SBT version that uses 2.11).

**Comment by drozzy** [comment]
@vkostyukov Thanks, much appreciated. Would be nice if this was indicated in the docs somewhere :-)
So what would I put as a repository url for bintray? (I assume it's not in default sbt repos...)

@travisbrown I think I get what you're saying, but it is rather confusing, since I, as a user, might not even know what version of scala my sbt uses :-)

**Comment by drozzy** [comment]
So I've managed to get my sbt to stop complaining... But now plugin doesn't actually do anything.

Here is my `build.sbt`:

```
name := "ierminer"

version := "1.0"

scalaVersion := "2.11.7"

resolvers += "Sonatype (releases)" at "https://oss.sonatype.org/content/repositories/releases/"

resolvers += "Twitter" at "http://maven.twttr.com"

libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.4" % "test"

libraryDependencies += "org.scala-lang" % "scala-reflect" % "2.11.7"

libraryDependencies += "org.scala-lang.modules" % "scala-xml_2.11" % "1.0.4"

libraryDependencies += "com.typesafe" % "config" % "1.3.0"

libraryDependencies += "info.cukes" % "cucumber-scala_2.11" % "1.2.4"

libraryDependencies += "junit" % "junit" % "4.12"

libraryDependencies += "info.cukes" % "cucumber-junit" % "1.2.4"

libraryDependencies += "com.typesafe.akka" %% "akka-actor" % "2.3.9"

libraryDependencies += "io.spray" %% "spray-client" % "1.3.3"

libraryDependencies += "com.twitter" % "scrooge-core_2.11" % "4.2.0"

libraryDependencies += "com.twitter" % "finagle-thrift_2.11" % "6.30.0"

libraryDependencies += "org.apache.thrift" % "libthrift" % "0.5.0-1"

mainClass := Some("distributed.Runner")
```

here is my `project/plugins.sbt`:

```
resolvers += "bintray" at "https://dl.bintray.com/twittercsl/sbt-plugins/"

addSbtPlugin("com.twitter" %% "scrooge-sbt-plugin" % "4.1.0")
```

I have a thrift definition in `src\main\scala\thrift\protocol.thrift`:

```
typedef string Item
typedef set<Item> Event

struct SeqEvent {
    1: i32 seq_id,
    2: Event event
}

struct TrackingRule {
    1: set<Item> left,
    2: set<Item> right,
    3: set<i32> supportive,
    4: set<i32> confident
}
```

but none of the target directories get any new compiled classes... :(

**Comment by notxcain** [comment]
@drozzy  Did you figure out how to make it work?

**Comment by ryanoneill** [comment]
FYI, I've updated the versions used in the Scrooge docs, specifically the SBTPlugin page.
http://twitter.github.io/scrooge/SBTPlugin.html

That may help.

**Comment by taylorleese** [comment]
@ryanoneill It looks like the quick start section of the readme.md needs updating as well and it also looks like @vkostyukov just released version 4.3.0 and the readme.md references version 4.2.0. We need to automate updating these versions everywhere including the places you updated in your recent commit.

**Comment by taylorleese** [comment]
@ryanoneill Can we close this once we clean up the versions?

**Comment by drozzy** [comment]
@notxcain No, I just gave up on it :-( 

Sorry I can't help you guys, I've switched to a different project.

**Comment by sundargates** [comment]
`resolvers += Resolver.url(
  "bintray-csl-sbt-plugins",
  url("https://dl.bintray.com/twittercsl/sbt-plugins"))(
  Resolver.ivyStylePatterns)`

- Adding the above to build.sbt resovles scrooge-sbt-plugin successfully

**Comment by mosesn** [comment]
Thanks @sundargates !
