### ISSUE TITLE
Sbt cannot start with scrooge-plugin 4.1.0 and http://maven.twttr.com resolver

### ISSUE THREAD

**Issue by vpavkin** [twitter/scrooge#213]
It failes to resolve dependency `"org.apache.thrift" % "libthrift" % "0.5.0-1"`. http://maven.twttr.com doesn't have it.

A workaround is to add http://mirrors.hypo.cn/twttr-maven/ to resolvers, it has this jar.

**Comment by mosesn** [comment]
@vpavkin I think maven.twttr.com should have [it][0], but you might need to use https to access it.

[0]: https://maven.twttr.com/org/apache/thrift/libthrift/0.5.0-1/

**Comment by vpavkin** [comment]
OMG... thanks! :)
Sorry for stupid issue.
