### ISSUE TITLE
generate scala code if Enum is not found throw exception

### ISSUE THREAD

**Issue by futureskywei** [twitter/scrooge#216]
I use scrooge generate scala client code, if the thrift server add a new  value to Enum , the client can't recognize it and it will throw NoSuchElementException.But I don't think it should throw exception.It should return null if the value is not found.
the scala result : 
  def apply(value: Int): com.twitter.finagle.thrift.order.OrderAuditingState =
    value match {
      case 1 => com.twitter.finagle.thrift.order.OrderAuditingState.ScalperPassWait
      case 3 => com.twitter.finagle.thrift.order.OrderAuditingState.ScalperAuditing
      case 4 => com.twitter.finagle.thrift.order.OrderAuditingState.WaitAuditing
      case 5 => com.twitter.finagle.thrift.order.OrderAuditingState.PintuanAuditing
      case _ => throw new NoSuchElementException(value.toString)
    }
the java result:
  public static OrderAuditingState findByValue(int value) {
    switch (value) {
      case 1:
        return SCALPER_PASS_WAIT;
      case 3:
        return SCALPER_AUDITING;
      case 4:
        return WAIT_AUDITING;
      case 5:
        return PINTUAN_AUDITING;
      default:
        return null;
    }

**Comment by kevinoliver** [comment]
For Scala, Scrooge generates also generates a `get(Int): Option[YourEnum]` and a `getOrUnknown(Int): Option[YourEnum]` method. Having `apply` fail seems like idiomatic Scala to me (e.g. `scala.collection.Map` follows this pattern).

In your use case, can you use one of the other two methods?

**Comment by mosesn** [comment]
I'm going to close this ticket, since I think it works as expected.
