### ISSUE TITLE
Output Directory scrooge-maven-plugin

### ISSUE THREAD

**Issue by leoneuwald** [twitter/scrooge#217]
I use scrooge-maven-plugin to generate java files in my project, but the plugin generate a folder named _scrooge_. (after _outputDirectory_ definition).

**Example:** 
- If **outputDirectory** is **C:\project\test** and the namespace in **File.thrift** is **namespace java com.app.thrift** the file output will be created in **C:\project\test\scrooge\com\app\thrift\File.java** instead of **C:\project\test\com\app\thrift\File.java**.

Is there a way to fix this?

**Comment by ryanoneill** [comment]
Hi @leoneuwald. We don't use maven much internally anymore, so the maven plugin is not something we are modifying much. If you'd like to take a crack at a pull request to be able to control where the files are output, we'd be happy to take a look. 

Based on a quick glance, it looks like the relevant area is https://github.com/twitter/scrooge/blob/develop/scrooge-maven-plugin/src/main/java/com/twitter/AbstractMavenScroogeMojo.java#L279

**Comment by leoneuwald** [comment]
Hi @ryanoneill tks for help.

I'll submit a pull request. And, in your opinion the file output must be configured only in tag **outputDirectory** or we need other tag to hide the _word scrooge_ of file output? I prefer the first one alternative.

Tks.

**Comment by ryanoneill** [comment]
I would tend towards creating a new tag that if not present defaults to 'scrooge', and so works as it does today by default. I don't recall best practices for pom files though. Is it good practice to have a tag with an empty value (which is what you would want in this case)? 

@kevinoliver, @cacoco have any thoughts?

**Comment by kevinoliver** [comment]
I don't know best practices for maven plugins, but I agree with the sentiments of keeping it work as it does today.

**Comment by cacoco** [comment]
I agree that unfortunately we need to be able to maintain the current behavior. It should be fine to create another parameter (e.g., a boolean) which specifies if the default of "scrooge" should be used and can override to simply exclude it. My suggestion would be "includeOutputDirectoryNamespace" which by default would be "true" in this case and give you the current behavior. You could then set it to false and it would not add the "scrooge" namespace.

Thanks!

**Comment by leoneuwald** [comment]
@cacoco @ryanoneill @kevincrane,

I'll submit a pull request with your suggestions in next week.

Thanks!

**Comment by mosesn** [comment]
@leoneuwald do you think you'll still have a chance to tackle this?

**Comment by leoneuwald** [comment]
@mosesn I created the pull resquest #245

**Comment by mosesn** [comment]
This was fixed a while back in #245 thanks @leoneuwald!
