### ISSUE TITLE
Non-case class ServiceIface generated when using scala 2.11 if service contains more than 22 functions

### ISSUE THREAD

**Issue by babyman** [twitter/scrooge#219]
Preface: I am new to thrift so this could easily be my mistake, if it is any help would be much appreciated =)

However it seems that when generating services with more than 22 functions the template suppresses the "case" statement for the generated ServiceIface class even when the SBT project declares its Scala version as 2.11.x.  This is causing issues when I try to enhance the functions with filters.

The code in this (https://github.com/twitter/scrooge/commit/7a12bf6fbf4cc7d282314fff8e77234263a32a57) commit relates to the template suppression but it looks like it's the Scala version check that's the issue.

I have created a minimal project to illustrate the issue I am having here https://github.com/babyman/thrift_test, hopefully it contains enough information to help (a clone and `./sbt clean compile` should be all that's required to see the problem).

Thanks,

Evan

**Comment by kevinoliver** [comment]
@babyman sorry for the delay in getting to this. I don't fully understand the issue you are seeing. Do you think the issue is in [here](https://github.com/twitter/scrooge/blob/develop/scrooge-generator/src/main/scala/com/twitter/scrooge/backend/ServiceTemplate.scala#L267-L277)?

**Comment by babyman** [comment]
@kevinoliver I think the issue manifests itself there though I'm not quite sure how, on my system (with this project https://github.com/babyman/thrift_test and my main project) this block returns true if I define more than 22 methods in the remote service even though I'm sure I'm using Scala 2.11.x:

```scala
Properties.releaseVersion.exists(_.startsWith("2.10"))
```

If less than 22 methods are defined the expected case class is generated.

```sh
MBA:thrift_test evan$ ./sbt
[info] Loading project definition from /Users/evan/projects/test-projects/thrift_test/project
[info] Set current project to thrift test (in build file:/Users/evan/projects/test-projects/thrift_test/)
> inspect scalaVersion
[info] Setting: java.lang.String = 2.11.7
[info] Description:
[info] 	The version of Scala used for building.
[info] Provided by:
[info] 	{file:/Users/evan/projects/test-projects/thrift_test/}root/*:scalaVersion
[info] Defined at:
[info] 	/Users/evan/projects/test-projects/thrift_test/build.sbt:7
[info] Reverse dependencies (D=derives):
[info] 	  *:allDependencies
[info] 	  *:scalaInstance
[info] 	  *:update
[info] 	  *:evicted
[info] 	  *:libraryDependencies
[info] 	D *:crossScalaVersions
[info] 	D *:scalaBinaryVersion
[info] Delegates:
[info] 	*:scalaVersion
[info] 	{.}/*:scalaVersion
[info] 	*/*:scalaVersion
[info] Related:
[info] 	*/*:scalaVersion
>
```

I wonder if SBT is running the code generator in a different context than my project?

**Comment by kevinoliver** [comment]
Looks pretty odd. Dunno what's going on there though.

**Comment by mosesn** [comment]
Could it be checking the scala version of sbt, rather than what it's trying to build?

**Comment by babyman** [comment]
@mosesn that would make sense, I don't see any way to pass the target build Scala version into the code generator (but I haven't had time to really search), I do have Scala on my system path but that is also 2.11.7:

```sh
$ scala -version
Scala code runner version 2.11.7 -- Copyright 2002-2013, LAMP/EPFL
```

I use this script to launch SBT for the project:

```sh
#!/bin/bash

sbtver=0.13.11
sbtjar=sbt-launch.jar
sbtsha128=7435a957b62743d81ae257c60bce11a641aef2a8

sbtrepo=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch

if [ ! -f $sbtjar ]; then
  echo "downloading $sbtjar" 1>&2
  if ! curl --location --silent --fail --remote-name $sbtrepo/$sbtver/$sbtjar; then
    exit 1
  fi
fi

checksum=`openssl dgst -sha1 $sbtjar | awk '{ print $2 }'`

if [ "$checksum" != $sbtsha128 ]; then
  echo "bad $sbtjar checksum $checksum.  delete $sbtjar and run $0 again."
  exit 1
fi

[ -f ~/.sbtconfig ] && . ~/.sbtconfig

java -ea                          \
  $SBT_OPTS                       \
  $JAVA_OPTS                      \
  -Djava.net.preferIPv4Stack=true \
  -XX:+AggressiveOpts             \
  -XX:+UseParNewGC                \
  -XX:+UseConcMarkSweepGC         \
  -XX:+CMSParallelRemarkEnabled   \
  -XX:+CMSClassUnloadingEnabled   \
  -XX:ReservedCodeCacheSize=128m  \
  -XX:SurvivorRatio=128           \
  -XX:MaxTenuringThreshold=0      \
  -Xss8M                          \
  -Xms512M                        \
  -Xmx2G                          \
  -server                         \
  -jar $sbtjar "$@"
```

**Comment by mosesn** [comment]
I don't think we can change sbt's scala version, it's probably best if we pass the scala version as a parameter to the generator.  http://stackoverflow.com/questions/26493088/how-can-one-pass-the-scala-version-string-to-a-code-generator-for-sbt looks like exactly what we're looking for.

**Comment by mosesn** [comment]
We no longer support 2.10, so we should just switch to generating 2.11-style all the time.

**Comment by kevinoliver** [comment]
I believe this was addressed with https://github.com/twitter/scrooge/commit/c391570cb30fc82a8b1189a5fdfd1928de89823c
