### ISSUE TITLE
Build is failing icon

### ISSUE THREAD

**Issue by 0xABAB** [twitter/scrooge#222]
You use some CI tool which shows that the build is failing. Either remove the icon or fix the problem.

**Comment by mosesn** [comment]
@0xABAB welcome to the scrooge community!  Good catch, would you like your first contribution to be helping us understand why it failed and fixing it?  Looking around at the logs, it looks like sbt can't find the main method anymore.  I think this would be a great way for you to join the community 😻

**Comment by 0xABAB** [comment]
Uhm, if your software falls apart, you just have to hire more people, not beg for other people to fix your issues. 

I am more than capable of fixing any software issue, but that doesn't mean I have a high interest in fixing your software. 

I think it's a rather pathetic statement for a company like Twitter. It makes Twitter look weak. I wouldn't want to be associated with beggars.

**Comment by mosesn** [comment]
Hi @0xABAB, Twitter is a microblogging website, and open sources its tools because it wants to give back to the community.  We don't work for you, and we have limited bandwidth.  Demanding that we do something, or being rude will not help either of us.  While you're participating in the twitter open source community, please follow the Twitter [code of conduct][0].

[0]: https://engineering.twitter.com/opensource/code-of-conduct

**Comment by yschimke** [comment]
@0xABAB I'm with you, some of us have lower tolerance for such shoddy work.  I can't unsee this now you pointed it out!

I installed the Stylebot chrome after you pointed out this problem, and the following script will hide this icon.  I realise you could have done this yourself, but we should share our small victories.

```
img[data-canonical-src="https://travis-ci.org/twitter/scrooge.svg?branch=develop"] {
    display: none;
}
```

I hope this helps, maybe @mosesn could agree at least update this thread after they *finally* fix the build and then we can both remove this workaround.

**Comment by 0xABAB** [comment]
> Twitter is a microblogging website, and open sources its tools because it wants to give back to the community.

Man, you are killing me. That's just hilarious. Twitter has a self-interest in getting more people to work with their code and tools; that is why it is open-sourced. Not because Twitter believes in some culture of sharing (it would have been a foundation, not a company in that case). It would be "giving back", if no contribution from the community had ever been done, because it was already perfect at release time. Any contribution back from the community, makes it a more symbiotic relation at first, but the very first bug fixed by the community is just pure profit. The very fact that I pointed out this issue, is something a PM would normally do; a PM you would normally have to pay. 

>  Demanding that we do something, or being rude will not help either of us.

I don't demand anything. I just say which work needs to be done. Who actually does it is of no concern to me. I have my reasons for opening issues in projects I am considering to use. Whether or not it actually gets fixed is hardly of interest to me. What is important is the amount of drama involved. In this case the drama is so high (perhaps you are micro-blogging all day long, which makes you good at drama, but made you forget about your job). That would be a reason for me (and hopefully others) to never start using this software in the first place (which is, of course, the direct opposite of your corporate goals). Isn't this multi-agent game called "open-source"-development fun?  

> While you're participating in the twitter open source community, please follow the Twitter code of conduct.

Oh man, you really lack any kind of social insight, right? I also believe you don't know the meaning of the word "community".     

@yschimke I have little interest in stylistic improvements, but I do appreciate your efforts (with the exception of your voting bullshit). 

As far as the rest of these clowns down voting, please grow a spine. 

@TwitterHQ: please hire some more competent people next time. These people are destroying your brand (or whatever is left of it).

**Comment by mosesn** [comment]
The build passes, so I'm going to mark this as fixed.

**Comment by taylorleese** [comment]
It's actually failing again. https://travis-ci.org/twitter/scrooge/builds

**Comment by mosesn** [comment]
The build has been passing pretty consistently: https://travis-ci.org/twitter/scrooge/builds
