### ISSUE TITLE
Automatically generate your documentation

### ISSUE THREAD

**Issue by 0xABAB** [twitter/scrooge#223]
In the README.md file you have the following text:

```
val scroogeCore = "com.twitter" %% "scrooge-core" % "3.3.2"
```

This does *not* work and using it as instructions is just amateur hour. 

Note, that I am not requesting for some guy to just update it and put in place a temporary hack. I am also not interested in a version which would currently work (e.g. in a comment).

**Comment by mosesn** [comment]
@0xABAB Hey!  Welcome to the scrooge project, and thanks for filing an issue.  We do update the versions, but only in our published documentation, in the user guide, which has better tools for keeping the version current than in the README.  Would you like to delete that part of the README quickstart and make a PR?

**Comment by mosesn** [comment]
I've fixed this, and the fix has been merged internally.
