### ISSUE TITLE
Having trouble compiling thrifts which form a DAG

### ISSUE THREAD

**Issue by jcoveney** [twitter/scrooge#232]
https://gist.github.com/jcoveney/e36c63f21392ccb9de0b738b44b4b57b

Basically, I have A struct and B struct, and want A to depend on B. Seems really weird that this isn't working, so clearly I'm doing something wrong. I've tried the command line and the sbt plugin

**Comment by klingerf** [comment]
I'm pretty sure that the ordering of the struct definitions in the file matters.  If AStruct contains a field that references BStruct, then BStruct has to be defined before AStruct.  So this should work:

```
struct BStruct {
  1: string a_field
}

struct AStruct {
  1: BStruct a_field
}
```

**Comment by johnynek** [comment]
@klingerf these are in two different files with an import.

**Comment by klingerf** [comment]
@johnynek Ah, right -- sorry, read the gist too quickly.

**Comment by kevinoliver** [comment]
@jcoveney as far as i know this is supported. not sure why its not working for you though as i haven't done much importing on either the dev or usage side.

did you see the example thrift files under [relative](https://github.com/twitter/scrooge/tree/develop/scrooge-generator-tests/src/test/thrift/relative)?

oh, hmm. do you need to refer to it as `BStruct.BStruct`?

**Comment by jcoveney** [comment]
annnnnd that is the fix. thanks so much, everyone! <3

**Comment by jcoveney** [comment]
[![selfie-0](http://i.imgur.com/6hyKfK6.png)](https://github.com/thieman/github-selfies/)
