### ISSUE TITLE
SBT plugin claims all generated sources were it's doing

### ISSUE THREAD

**Issue by philwills** [twitter/scrooge#233]
https://github.com/twitter/scrooge/blob/develop/scrooge-sbt-plugin/src/main/scala/com/twitter/ScroogeSBT.scala#L243 claims that the Scrooge SBT plugin has generated all classes with the appropriate extension in the managed sources directory. This assumption falls down, causing compilation failures, if a project is also using another plugin, such as sbt-buildinfo (https://github.com/sbt/sbt-buildinfo/issues/88), which generates scala sources.

**Comment by benjumanji** [comment]
yeah, a better default for `scroogeThriftOutputFolder` would probably be the ticket.

**Comment by joprice** [comment]
I just hit this same issue. Found the suggested solution here: https://github.com/guardian/content-api-scala-client/blob/452f2a359c15b75a4baf1871b018ebe130895f88/build.sbt#L94. Any reason to not update this? If it has to stay the same for compat, seems like it should at least be in the docs.

**Comment by kevinoliver** [comment]
i personally don't have strong feelings regarding backwards compatibility if there is consensus about a better default. we'd need to document the break in `CHANGES`. please feel free to open a PR to get this started. that's where we can hear about reasons to keep compatibility.

**Comment by mosesn** [comment]
I think this change would be an improvement.

**Comment by mosesn** [comment]
JK looks like it's already in progress here: https://github.com/twitter/scrooge/pull/234!

**Comment by mosesn** [comment]
This was fixed a while back in #234, thanks @joprice!
