### ISSUE TITLE
since method originalName in trait ThriftEnum of type => String is not defined

### ISSUE THREAD

**Issue by lelence** [twitter/scrooge#235]
i use :  
twitter-server 1.20.0
finagle-thrift 6.35.0
scrooge-core  4.7.0
libthrift 0.9.3

if i add an Enum to the thrift, there while be an exception : 

class EnumUnknownRecordStatus needs to be abstract, since method originalName in trait ThriftEnum of type => String is not defined
[error]   case class EnumUnknownRecordStatus(value: Int) extends test.thrift.RecordStatus {
[error]              ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed

the thrift content is :

namespace java test.thrift
#@namespace scala test.thrift

enum RecordStatus {
  Active = 0
}

**Comment by kevinoliver** [comment]
what does your generated code for `EnumUnknownRecordStatus` look like? it sounds like you may have a mismatch between the versions of scrooge-code and the generator.

The `originalName` code was partially added in 74a6e432af6119 and then the rest was added in 6d26414101f35a. This was all part of the 4.7.0 release.

**Comment by lelence** [comment]
i set the scrooge-generator verion 4.6.0, there is also has the exception 

[error] /Users/Toan/git/scala-parent/thrift-rpc-server/target/scala-2.11/src_managed/main/test/thrift/RecordStatus.scala:23: class EnumUnknownRecordStatus needs to be abstract, since method originalName in trait ThriftEnum of type => String is not defined
[error]   case class EnumUnknownRecordStatus(value: Int) extends test.thrift.RecordStatus {
[error]              ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 9 s, completed 2016-5-13 9:33:14

if i remove the code of enum from the thrift file ,  the compile success.

**Comment by tsfto** [comment]
In my case, this was caused by failing to update the Scrooge sbt plugin to match the latest version. Using:

addSbtPlugin("com.twitter" %% "scrooge-sbt-plugin" % "4.7.0")

resolved the scrooge-generator mismatch.

**Comment by mosesn** [comment]
@lelence please let us know what happens when you make sure to align your scrooge-generator and scrooge-core!  You might need to change your plugin version if you use the scrooge-sbt-plugin or scrooge-maven-plugin.  I'm going to close for now, since @tsfto mentioned this fix works for him.
