### ISSUE TITLE
2.12-ification

### ISSUE THREAD

**Issue by mosesn** [twitter/scrooge#236]
In order to support 2.12, we need to add crossScalaVersions to Build.scala, and make sure everything compiles.  Not every scala library will be built against the current snapshot, so we may have to support different versions from 2.11 to 2.12.  If part of an API has churned (scalacheck in particular is susceptible to this) we may need to upgrade the 2.11 library version to make progress.  If that happens, contact me (@mosesn) and I'll navigate the upgrade for you–it's a little complicated because we will need to upgrade all of our internal libraries, not just scrooge.  Please note that most of this upgrade will not be feasible until we have a portion of util already upgraded.  We are not upgrading `scrooge-sbt-plugin`, because sbt is not migrating to [2.12 anytime soon](https://github.com/sbt/sbt/issues/2389).
- [x] scrooge-benchmark
- [x] scrooge-core
- [x] scrooge-generator
- [ ] scrooge-generator-tests
- [x] scrooge-linter
- [x] scrooge-maven-plugin
- [x] scrooge-serializer

If you want to claim a module, please let us know in this thread!  I'll annotate different modules once they're done.

Probably a good way to start is for someone to try add 2.12 support for all of them, and then report back which ones still fail, so we know which ones are tricky and which ones work trivially.

**Comment by taylorleese** [comment]
Related: https://github.com/twitter/util/issues/162

**Comment by mosesn** [comment]
We will need to make sure that mustache scala-extensions-2.11 works against scala 2.12.  We also need to upgrade to mustache 0.9.x (OK now that we're on jdk 8).

**Comment by jeffreyolchovy** [comment]
I'll take care of this one as well. See https://github.com/twitter/scrooge/pull/237 for current status.

**Comment by mosesn** [comment]
Almost everything here has been tackled by https://github.com/twitter/scrooge/pull/237.  scrooge-generator-tests is still waiting on finagle.  Thanks @jeffreyolchovy!

**Comment by sritchie** [comment]
Hey @mosesn, what's the status here? @johnynek and I are churning through the Summingbird dependencies; util looks like it's upgraded, but we're still waiting on Scrooge and Finagle. Do you have an ETA for a 2.12 build here?

Thanks!

**Comment by mosesn** [comment]
@sritchie scrooge is already on 2.12, so you shouldn't be blocked here.  the only thing that's not is the tests.  http://search.maven.org/#search%7Cga%7C1%7Cscrooge-core_2.12

2.12 introduced a backwards incompatible change that was a blocker for a while: https://github.com/twitter/finagle/issues/505.  We had to break one of our public-facing APIs to make forward progress and it was painful.  Now we're running into a scala compiler bug in 2.12, so it will probably be a little bit longer.

**Comment by sritchie** [comment]
Okay, nice! I'll see if we can get on to 4.12. Sorry for not noticing that.

**Comment by mosesn** [comment]
no worries–you probably need finagle too, so it might make sense to hold off for a little while.

**Comment by mosesn** [comment]
@sritchie we just published finagle on 2.12, so you should be good to go.

**Comment by mosesn** [comment]
We can resume work on this now that finagle-thrift has been published, so if anyone wants to tackle the scrooge-generator-tests, it should be pretty straightforward now!

**Comment by kevinoliver** [comment]
This was addressed in https://github.com/twitter/scrooge/commit/a37f2af058c4feb068d9bba6b987aa7e1b9787e6 and scrooge is 2.12-ified.
