### ISSUE TITLE
Self-references leads to error

### ISSUE THREAD

**Issue by nollbit** [twitter/scrooge#243]
Self-references leads to error

### Expected behavior

Self-referencing structs should be supported

### Actual behavior

Self-referencing structs leads to `TypeNotFoundException`

### Steps to reproduce the behavior

```
namespace java com.test.thrift

struct Hello {
	1: optional Hello hello;
}
```
This is supported by later Thrift compilers. I'm not sure this is a bug in Scrooge since afaik it has never promised to be fully Thrift compatible.

**Comment by kevinoliver** [comment]
Yeah, this is not supported today. This is the same as issue https://github.com/twitter/scrooge/issues/160 which has more commentary.
