### ISSUE TITLE
Getting weird error during decoding of a thrift class.

### ISSUE THREAD

**Issue by allquantor** [twitter/scrooge#251]
A get a weird error by encoding the thrift class
```
org.apache.thrift.transport.TTransportException: Cannot read. Remote side has closed. Tried to read 1044415 bytes, but only got 1019416 bytes.
```
Basically, it happens during the deserialization. I do use scala 2.11.8, Scrooge version: 4.12.0. 
Any idea?

**Comment by mosesn** [comment]
@allquantor make sure both client and server are using the same thrift protocol, and the same framing mechanism.  one thing that might be going on is that there's a mismatch in how the client and the server describe the bytes of the wire.

I'd encourage you to tcpdump the message and see if something funky is going on by just looking at the bytes directly.

**Comment by allquantor** [comment]
@mosesn Thanks for your reply. Actually, I ensured that my projects all use the same versions.

Here the list of twitter stack related libraries used in my projects:
com.twitter:scrooge-core_2.11:jar:4.12.0
com.twitter:scrooge-maven-plugin:4.12.0
com.twitter:finagle-http_2.11:jar:6.40.0
com.twitter:libthrift:jar:0.5.0-7
com.twitter:finagle-thrift_2.11:jar:6.40.0 

I also tried to look into the tcpdump, but this does not help me to clarify the situation. A new thing that I found out is that the amount of bytes missing is time-related. By working in debug mode I got different results. Here an example:

>  "message": "Cannot read. Remote side has closed. Tried to read 1044415 bytes, but only got 1019526 bytes.",
>  "message": "Cannot read. Remote side has closed. Tried to read 1044415 bytes, but only got 1019675 bytes.",
>  "message": "Cannot read. Remote side has closed. Tried to read 1044415 bytes, but only got 1019328 bytes.",
>  "message": "Cannot read. Remote side has closed. Tried to read 1044415 bytes, but only got 1019193 bytes.",


It would be great if somebody had at least an approach to find out more. Thanks in advance.

**Comment by allquantor** [comment]
Solved by myself. The solution was indeed interesting. I used finagle to send/receive Thrift objects. Well, if you send Octet-Streams you should use ByteStreams instead of CharStreams to encode your response and decode your payload. Chars (16 bits in Java) are encoded with two bytes, thus the losing of information. A change to handling the response as byte stream solved the issue.

If somebody have a similar problem feel free to contact me probably we can figure out it together.
