### ISSUE TITLE
Can not generate scala code with maven plugin

### ISSUE THREAD

**Issue by QuantumBear** [twitter/scrooge#253]
I use scrooge plugin try to generate Scala case class for some thrift class

### Expected behavior

Source files in target/generated-sources/thrift are Scala source files.

### Actual behavior

Source files in target/generated-sources/thrift are Java source files.

### Steps to reproduce the behavior

I added this dependency to my pom file, because our project stick to libthrift to 0.61 so I excluded libthrift.

    <dependency>
      <groupId>com.twitter</groupId>
      <artifactId>scrooge-core_${scala.binary.version}</artifactId>
      <version>4.6.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>org.apache.thrift</groupId>
          <artifactId>libthrift</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

Then add this plugin configuration to plugins section.

      <plugin>
        <groupId>com.twitter</groupId>
        <artifactId>scrooge-maven-plugin</artifactId>
        <version>3.14.1</version>
        <configuration>
          <thriftNamespaceMappings>
            <thriftNamespaceMapping>
              <from>com.mediav.data.log.unitedlog</from>
              <to>com.mediav.data.log.unitedlog</to>
            </thriftNamespaceMapping>
          </thriftNamespaceMappings>
          <language>scala</language> 
          
          <buildExtractedThrift>false</buildExtractedThrift>
        </configuration>
        <executions>
          <execution>
            <id>thrift-sources</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>thrift-test-sources</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

After that I run mvn clean install, but I only find generate Java files, but I actually need Scala files.

**Comment by kevinoliver** [comment]
@QuantumBear that looks right to me, but maybe there is a bug. We don't use the maven plugin here at Twitter so I don't have any good ideas. Maybe someone else out there is using the maven plugin and can advise.

**Comment by QuantumBear** [comment]
It turned out that I use other plugin to compile thrift file in parent pom, disable it then scrooge plugin works.
