### ISSUE TITLE
TApplicationException.read API change in thrift 0.10.0

### ISSUE THREAD

**Issue by dzanot** [twitter/scrooge#261]
The latest version (org.apache.thrift % libthrift % 0.10.0) of java thrift `TApplicationException` no longer has the static method `read(TProtocol iprot)` but the latest version of scrooge-core (4.14.0) is generating this method call via a service definition. 

### Expected behavior

[Here you can see](https://github.com/apache/thrift/blob/0.10.0/lib/java/src/org/apache/thrift/TApplicationException.java#L129) the static `read` was replaced by another static `readFrom` that wraps the newly de-static `read` method. I expect the compile to generate the new method. 

### Actual behavior

The compiler is in-fact generating the [old method](https://github.com/apache/thrift/blob/0.9.3/lib/java/src/org/apache/thrift/TApplicationException.java#L76), spitting out non-compiling (against 0.10.0) code. This may be intentional, I haven't been able to find a mapping of scrooge/thrift versions.

**Comment by taylorleese** [comment]
More details in https://github.com/twitter/scrooge/issues/85.

**Comment by dzanot** [comment]
Definitely. That issue didn't turn up in my searches.

**Comment by taylorleese** [comment]
@kevinoliver is going to spend some time in the next week or two looking at how much work would be involved in moving to 0.10.0 internally and then we should have an informed idea if this is feasible in the near term for us or not.

**Comment by mosesn** [comment]
@dzanot exciting update!  changing to 0.10.0 isn't as much work as we thought it would be so, we have [scheduled][0] it.  Should happen in the next few months.

[0]: https://finagle.github.io/blog/2017/03/20/spring-planning/

**Comment by wesselOC** [comment]
@taylorleese  Any idea when this is scheduled for ?  Much appreciated!

**Comment by mosesn** [comment]
@wesselOC it's on our plate for this quarter, but it's not the highest priority, so it might get delayed again.

**Comment by wesselOC** [comment]
@mosesn that would be a pity. Would you guys accept a pull request for something so core?

**Comment by kimxogus** [comment]
Are there any updates about this issue?

**Comment by kevinoliver** [comment]
_/me crosses fingers_

soon we hope. the code is done and we are waiting for some final rounds of verification and testing to come back.

**Comment by wesselOC** [comment]
Awesome news!

**Comment by yufangong** [comment]
@dzanot @wesselOC @kimxogus  Hi all, we upgrade libthrift to 0.10.0, it should solve this issue. If that is not the case please open another issue. Thank you all.
