### ISSUE TITLE
Cannot compile Hive's .thrift file- "field in union cannot be optional"

### ISSUE THREAD

**Issue by tejasmanohar** [twitter/scrooge#263]
I get 
>Field i32Value in union TTypeQualifierValue cannot be optional

when I try to generate a Scala server for [Hive's .thrift protocol](https://github.com/apache/hive/blob/3e01ef3268ffbcb69c5c18c2c9f8810512c91bf8/service-rpc/if/TCLIService.thrift).

```
$ ./sbt 'scrooge-generator/run-main com.twitter.scrooge.Main -d test /Users/tejas/dev/src/github.com/apache/hive/service-rpc/if/TCLIService.thrift'
[info] Loading project definition from /Users/tejas/dev/src/github.com/twitter/scrooge/project
Missing bintray credentials /Users/tejas/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to scrooge (in build file:/Users/tejas/dev/src/github.com/twitter/scrooge/)
[info] Running com.twitter.scrooge.Main -d test /Users/tejas/dev/src/github.com/apache/hive/service-rpc/if/TCLIService.thrift
[error] (run-main-0) com.twitter.scrooge.frontend.FileParseException: Exception parsing: /Users/tejas/dev/src/github.com/apache/hive/service-rpc/if/TCLIService.thrift
com.twitter.scrooge.frontend.FileParseException: Exception parsing: /Users/tejas/dev/src/github.com/apache/hive/service-rpc/if/TCLIService.thrift
Caused by: com.twitter.scrooge.frontend.FileParseException: Exception parsing: /Users/tejas/dev/src/github.com/apache/hive/service-rpc/if/TCLIService.thrift
Caused by: com.twitter.scrooge.frontend.UnionFieldOptionalException: Field i32Value in union TTypeQualifierValue cannot be optional
[trace] Stack trace suppressed: run last scrooge-generator/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last scrooge-generator/compile:runMain for the full output.
[error] (scrooge-generator/compile:runMain) Nonzero exit code: 1
[error] Total time: 1 s, completed Mar 12, 2017 12:56:18 PM
```

### Expected behavior

Scrooge to compile Hive Thrift RPC files just like the Thrift CLI does for Java

### Actual behavior

Crashes with an exception

### Steps to reproduce the behavior

1. Download [Hive's .thrift file](https://github.com/apache/hive/blob/3e01ef3268ffbcb69c5c18c2c9f8810512c91bf8/service-rpc/if/TCLIService.thrift)
2. Run `scrooge-generator/run-main com.twitter.scrooge.Main .../TCLIService.thrift`

PS: I'm new to Scrooge, Scala, and Thrift so I may be missing something. I'd _expect_ it to work just like the official tool. Is this a known caveat of Scrooge?

**Comment by macalinao** [comment]
From the scrooge changelist:

> - Introduce a "strict" mode that defaults to on. Unfavored syntax throws an
> exception when "strict" mode is on and prints a warning when it's off. The
> strict mode can be disabled by specifying the "--disable-strict" argument.

You need to not be in strict mode for this.

**Comment by mosesn** [comment]
@tejasmanohar I think your question has been answered, so I'm going to mark this as closed.  Feel free to reopen if you still have questions!
