### ISSUE TITLE
fieldInfo is not defined in unionStructFieldInfo for list types

### ISSUE THREAD

**Issue by muuki88** [twitter/scrooge#264]
The `unionStructFieldInfo` method is incorrectly implemented for `list` types

### Expected behavior

scrooge generates compilable scala code

### Actual behavior

scrooge generates scala code that access a non-existing field

### Steps to reproduce the behavior

We have a thrift definition like this

```thrift
struct IdNameTuple
{
    1: required i32 id,
    2: required string name,
    3: required string identifier
}

enum IdNameTupleErrorReason
{
    UNEXPECTED_ERROR, TABLE_DOES_NOT_EXIST
}

struct IdNameTupleError
{
    1: required IdNameTupleErrorReason reason,
    2: optional string description
}

union IdNameTupleResponse
{
    1: list<IdNameTuple> IdNameTupleList,
    2: IdNameTupleError error
}
```

The resulting `IdNameTupleList` has the following code generated:

```scala

  case class IdNameTupleList(
      IdNameTupleList: IdNameTupleListAlias = IdNameTupleListDefaultValue)
    extends IdNameTupleResponse {

    protected type ContainedType = IdNameTupleListAlias

    def containedValue(): ContainedType = IdNameTupleList

    // this doesn't compile as 'fieldInfo' is not defined
    def unionStructFieldInfo: _root_.scala.Option[ThriftStructFieldInfo] =
      _root_.scala.Some(IdNameTupleList.fieldInfo)
```

**Comment by mosesn** [comment]
oof.  is the issue when you try to have a union over a thrift-defined data structure?

**Comment by muuki88** [comment]
Yeah, looks like this. The `list<IdNameTuple> IdNameTupleList` generates a `Seq[IdNameTuple]` ( == `IdNameTupleListAlias`) which has no `fieldInfo` field.

I can work around this by create a struct wrapping the list. However it would be nice to either document this restriction and throw a meaningful error, or support this.

**Comment by muuki88** [comment]
I found the real issue. Using an extract struct didn't solve the problem, which made me wonder. 
The fieldname in the union field definition starts with a capital letter

```
1: list<IdNameTuple> IdNameTupleList
```

Changing this to

```
1: list<IdNameTuple> idNameTupleList
```

Solves the issue as the correct variable is used and not the `IdNameTupleList` object.

**Comment by mosesn** [comment]
Ahhh, good catch!
