### ISSUE TITLE
Support sbt 1.0 for scrooge-sbt-plugin in bintray

### ISSUE THREAD

**Issue by greggdonovan** [twitter/scrooge#275]
With sbt 1.0 out, it would be great to support sbt 1.0 cross-building and artifact publishing for scrooge-sbt-plugin. 

I see [sbt 1.0 support for dodo](https://github.com/twitter/scrooge/commit/251cf2918d3371de4599a9777ed1980423202431) but there does not appear to be sbt 1.0 artifact publishing for the external bintray repository.

**Comment by mosesn** [comment]
@greggdonovan good news!  we're planning on publishing for 1.0.0 next release.  we were going to do it this time, but ran into a few problems around it, so it didn't make the cut.  next release should be early September.

**Comment by dazebug** [comment]
Does anybody know when is the next release? We are eagerly waiting for the plugin Lol

**Comment by mosesn** [comment]
@dazebug still working on it, sorry!  The next release came out, but I'm having trouble testing the 1.0.0 plugin so we decided not to include it this time.  Right now we're probably looking at early October :/

**Comment by gpoirier** [comment]
Any update on this? It's the only plugin that prevents us from using sbt 1.0.

**Comment by mosesn** [comment]
Sorry, I got pulled off onto something else, and haven't had a chance to revisit this.  I'm oncall this week, so if things aren't too crazy on my end I'll try to take another look.  The last time we tried we ran into a couple of issues around it.

**Comment by mosesn** [comment]
we merged in support for this [here](https://github.com/twitter/scrooge/commit/d3499b89fbee72766d95b89e3f7c323272b3dce7) and we're planning on doing a release soon.  thanks for your patience folks!

**Comment by mentegy** [comment]
good job guys, can't wait for it!

**Comment by mentegy** [comment]
@mosesn Do you have a date of 17.11.0 release?

**Comment by mosesn** [comment]
@mentegy I'm working on it as we speak =).  there have been a few more issues around 1.0.x, unfortunately.

**Comment by mosesn** [comment]
We've published a new release, 17.11.0, which should support 1.0.x.  Please try it out and let me know if you run into any issues!

**Comment by mentegy** [comment]
@mosesn works great so far, gratz!

**Comment by mosesn** [comment]
@mentegy ok, phew, glad to hear it!
