### ISSUE TITLE
Scrooge 4.20 generates Adapting argument list by creating a 2-tuple warning

### ISSUE THREAD

**Issue by devshorts** [twitter/scrooge#277]
When upgrading to scrooge 4.20 our generated thrift clients now emit a 

```
UserSettingsService$FinagleService.scala:103: Adapting argument list by creating a 2-tuple: this may not be what you want.
[error]         signature: Service.apply(request: Req): com.twitter.util.Future[Rep]
[error]   given arguments: iprot, msg.seqid
[error]  after adaptation: Service((iprot, msg.seqid): (org.apache.thrift.protocol.TProtocol, Int))
[error]           svc(iprot, msg.seqid)
[error]              ^
```

This is a new warning that didn't exist in at least scrooge 4.16 using both scala 2.12 and scala 2.11

### Expected behavior

Scrooge should be generated to not have this warning

### Actual behavior

Scrooge has the warning

### Steps to reproduce the behavior

Generate thrift with scrooge 4.20

**Comment by kevinoliver** [comment]
Good find, thanks. Want to take a crack at a fix? I think it would be adding parens [here](https://github.com/twitter/scrooge/blob/develop/scrooge-generator/src/main/resources/scalagen/finagleService.scala#L112).

**Comment by kevinoliver** [comment]
@samschlegel apologies for messing up on the commit as i lost your authorship. hope this isn't a problem.

**Comment by samschlegel** [comment]
No worries 😊
