### ISSUE TITLE
No such method error creating thrift client on java 9

### ISSUE THREAD

**Issue by devshorts** [twitter/scrooge#286]
No such method error when running on java 9

### Actual behavior

Testing some code of mine on java 9 (9.0.4) and seeing the following error trying to create a thrift client:

```
Caused by: java.lang.NoSuchMethodError: org.apache.thrift.protocol.TBinaryProtocol$Factory.<init>
(ZZI)V at com.twitter.finagle.thrift.Protocols$.binaryFactory(Protocols.scala:71) at com.twitter.finagle.Thrift$.<init>(Thrift.scala:133) at com.twitter.finagle.Thrift$.<clinit>
(Thrift.scala) at com.curalate.services.socialmining.thrift.MiningService$FinagleService.<init>
(MiningService$FinagleService.scala:45) at com.curalate.services.socialmining.thrift.MiningService$FinagledService.<init>
(MiningService.scala:16384)
```

### Steps to reproduce the behavior

using `finagle-thrift_2.12-7.1.0` 

Oddly enough running my code in java 9 in intellij works just fine. However, when I run my code via sbt (with fork true) I get this error.  I'm not sure what is going on other than it seems java 9 related as the path that was hit looks to be checking for some compact string stuff

**Comment by yufangong** [comment]
@devshorts  thanks for the report. This smells like a version conflict problem of libthrift, scrooge depends on 0.5.0, do you depend on any other versions as well?

**Comment by devshorts** [comment]
@yufangong hmm, we have libthrift 0.9.3 from apache on the classpath.  I dont' remember why we added it, so I'll dig into it. Is the recommendation to just use the thrift that is pulled in transitively via finagle-thrift?

**Comment by yufangong** [comment]
Currently, libthrift 0.9.x is not compatible with 0.5.0, it has some breaking API changes, so I think it is good to avoid version conflict. And we are upgrading libthrift to 0.10.0 now, will rollout after all tests are done.

**Comment by yufangong** [comment]
Hi @devshorts, we upgraded libthrift to 0.10.0, it should solve this issue. If that is not the case please open another issue. Thank you.
