### ISSUE TITLE
not possible to implement multiple services in one class

### ISSUE THREAD

**Issue by ccmtaylor** [twitter/scrooge#298]
PHAB_ID=D129645 added `.asClosable` methods to `MethodPerEndpoint` interfaces. If a class implements multiple interfaces, it must override `asClosable` to avoid compiler errors. However, it is
not possible.

### Expected behavior

I can implement multiple `ServicePerEndpoint` interfaces in one class.

### Actual behavior

the compiler complains about conflicting members.
```
if we don't override `asClosable`, the compiler says:
Error:(6, 7) class FooImpl inherits conflicting members:
  method asClosable in trait ExtendedEcho of type => com.twitter.util.Closable  and
  method asClosable in trait Echo of type => com.twitter.util.Closable
(Note: this can be resolved by declaring an override in class FooImpl.)
```
As far as I can tell, it is not possible to override `asClosable`, to delegate to both inherited methods.

### Steps to reproduce the behavior

I created a test-case at https://github.com/ccmtaylor/scrooge-multiple-inheritance. When you un-comment [lines 23-24](https://github.com/ccmtaylor/scrooge-multiple-inheritance/blob/master/src/main/scala/multi/EchoImpl.scala#L23-L24) of the service implementation, it results in invalid syntax; commenting out the whole method produces the above-mentioned error message.

**Comment by yufangong** [comment]
@ccmtaylor Hi, can you elaborate more why you want one class implement multiple services' MethodPerEndpoint? I wonder if the `Echo` should actually extends `ExtendedEcho`
```
service ExtendedEcho extends Echo {
  string getStatus();
}
```
In that case, it should work by only letting the class extended the `ExtendedEcho.MethodPerEndpoint`.

**Comment by cacoco** [comment]
@ccmtaylor +1 to @yufangong. It is expected that you express the relationship between the two services in your thrift definition and your implementation would be of the child service. This would have all methods from the parent in addition to it's own to be implemented and only one `asClosable` function.

**Comment by ccmtaylor** [comment]
Thanks for the feedback, @yufangong and @cacoco! You're right, using inheritance would address the issue for the example I provided. However, this would not work if the two interfaces were disjoint (imagine, e.g., an internal- and an external-facing API for some domain entity).

If this is not a supported use-case anymore, would it make sense to document that an implementation class can only implement a single `MethodPerEndpoint`?

**Comment by cacoco** [comment]
@ccmtaylor if the interfaces are disjoint -- this isn't supported by Thrift. See: https://thrift.apache.org/docs/features

You're expected to design a service and services can inherit other services. There's no other polymorphism supported. So I'm not sure what would be the expected behavior here for a generator or generated code?

**Comment by yufangong** [comment]
@ccmtaylor It is not supported as @cacoco said, any reason you cannot use separate servers? I think this is a rare case and we haven't received any similar feedback before, the doc and code examples [here](https://twitter.github.io/scrooge/Finagle.html#methodperendpoint) are pretty clear,  And I'm worried about adding this note may lead users to overthink.
