### ISSUE TITLE
Scrooge can not handle empty structs

### ISSUE THREAD

**Issue by zivanfi** [twitter/scrooge#303]
Empty stucts lead to a compilation error:

```
[510.1] failure: string matching regex `[A-Za-z_][A-Za-z0-9\._]*' expected but `}' found
```

### Background

In the Apache Parquet project we would like to update our Scrooge dependecy from the ancient Scrooge 3.17.0 to a newer version. However, we have found that Scrooge 19.1.0 doesn't handle empty structs properly any more. [We have several such structs in Parquet](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift), some of these are just left empty temporarily, while others are never meant to contain any attributes (they are used in unions, essentially giving us an enum that can be extended with new values and various attributes). For example:

```
struct IndexPageHeader {
  /** TODO: **/
}
```
```
/** Empty structs to use as logical type annotations */
struct StringType {}  // allowed for BINARY, must be encoded with UTF-8
struct UUIDType {}    // allowed for FIXED[16], must encoded raw UUID bytes
struct MapType {}     // see LogicalTypes.md
struct ListType {}    // see LogicalTypes.md
struct EnumType {}    // allowed for BINARY, must be encoded with UTF-8
struct DateType {}    // allowed for INT32
```

These structs are completely valid in Thrift and they used to work fine with Scrooge 3. In Scrooge 19, however, they lead to a compilation error:

```
Exception parsing: parquet-mr/parquet-scrooge/target/generated-resources/parquet.thrift:
[510.1] failure: string matching regex `[A-Za-z_][A-Za-z0-9\._]*' expected but `}' found
```

**Comment by nandorKollar** [comment]
Though this seems to be a problem in the parser, I think removing the comment from the struct (/** TODO: **/) cold be a workaround.

**Comment by zivanfi** [comment]
Ah, okay, I think I get it now. The problem is that this comment is a javadoc-style (/**), therefore scrooge expect to find an attribute following it that the comment applies to. In this case it really is an error in our thrift file (although the error message could be clearer). Resolving as "not a bug", thanks!
