### ISSUE TITLE
scalagen: Instance of ServicePerEndpoint trait should apply filter when using filtered function

### ISSUE THREAD

**Issue by anusha-mallampati-ck** [twitter/scrooge#306]
Implementing ServicePerEndpoint trait and using `filtered` on its instance does not apply filters. Using ServicePerEndpoint.apply does apply the filters.

### Expected behavior

For a service, if you create a class that extends its ServicePerEndpoint trait and use `filtered` function on its instance, the filter should be applied.

### Actual behavior

Filter(s) are not applied

### Steps to reproduce the behavior

Create a service `TestService`.

Implement it in the below way:

```
class TestServiceImpl extends TestService.ServicePerEndpoint { ??? }

class ExampleFilter extends TypeAgnostic { ??? }
```

Apply a filter to it's instance

```
val service = new TestServiceImpl

service.filtered(new ExampleFilter) //should apply filter, but does not apply the filter

```

**Comment by ryanoneill** [comment]
Hi @anusha-mallampati-ck, I'm looking into this, and I'll let you know what I find.

**Comment by ryanoneill** [comment]
I'm seeing what you see. Here's my rough code for reproducing:

```scala
class TestServiceImpl extends TestService.ServicePerEndpoint {

  val query = new Service[Query.Args, Query.SuccessType] {
    def apply(args: Query.Args): Future[Query.SuccessType] = {
      println("Hello from query")
      Future.value(args.x)
    }
  }

  val reverse = new Service[Reverse.Args, Reverse.SuccessType] {
    def apply(args: Reverse.Args): Future[Reverse.SuccessType] = {
      println("Hello from reverse")
      Future.value(args.x.reverse)
    }
  }

}
```
```scala
class ExampleFilter extends Filter.TypeAgnostic {

  def toFilter[Req, Rep]: Filter[Req, Rep, Req, Rep] = {
    new SimpleFilter[Req, Rep] {
      def apply(request: Req, service: Service[Req, Rep]): Future[Rep] = {
        println("Hello from ExampleFilter")
        service(request)
      }
    }
  }

}
```

```scala
val service = new TestServiceImpl
ThriftMux.server.serveIface(":8080", service.filtered(new ExampleFilter).toThriftService)

val client = ThriftMux.client.build[TestService.MethodPerEndpoint]("localhost:8080", "myclient")
Await.result(client.query("xyz"))
Hello from query
... String = xyz
```
```scala
val service2 = TestService.ServicePerEndpoint.apply(service.query, service.reverse)
ThriftMux.server.serveIface(":8081", service2.filtered(new ExampleFilter).toThriftService)

val client2 = ThriftMux.client.build[TestService.MethodPerEndpoint]("localhost:8081", "myclient2")
Await.result(client2.query("xyz"))
Hello from ExampleFilter
Hello from query
... String = xyz
```

**Comment by ryanoneill** [comment]
Dug a little bit farther on this and the short answer is that when you extend 'TestService.ServicePerEndpoint', you should also be overriding the filtered implementation with one of your own. 

In talking with some other folks on our team, Scrooge has poor visibility into the implementation of your class and thus doesn't know exactly how filtered should work in this scenario. I'm going to see what our options are here, which may just be documenting this better within the Scrooge documentation. 

Thanks for reporting.

**Comment by anusha-mallampati-ck** [comment]
@ryanoneill Is there a reason for making the default behavior of `filtered` on the ServicePerEndpoint trait not the same as the one on the object apply result (ServicePerEndpointImpl)? 

I agree that folks should override based on their unique implementation, but shouldn't that be only necessary if they are doing something different with `filtered` other than just `filter.toFilter.andThen(someEndpoint)`?

Thanks for looking into this.

**Comment by ryanoneill** [comment]
I agree with you. In discussion with some teammates, there may be issues related to the fact that the trait can be extended. I'm looking into it, and trying to verify that calling essentially `ServicePerEndpoint.apply(...).filtered(filter)` is ok in all scenarios.

**Comment by ryanoneill** [comment]
This has made its way to GitHub in commit https://github.com/twitter/scrooge/commit/e46b2785d036b2f6920eea9aefb5a93307618231 and will be in the next released version of Scrooge (likely by next week).

**Comment by anusha-mallampati-ck** [comment]
Thank you!
