### ISSUE TITLE
Support Scala 2.13 RC1 and beyond

### ISSUE THREAD

**Issue by skonto** [twitter/scrooge#308]
`scrooge-serializer` is required by several projects, like chill which is used again by many other projects like Spark. Would be good to start supporting 2.13 as it will be soon out.

**Comment by ayoub-benali** [comment]
tried to build but it seems to be blocked by this PR https://github.com/twitter/util/pull/248 at least

**Comment by martijnhoekstra** [comment]
twitter/util is released, but not yet published.

As long as sbt is stuck on 1.1.4 for cross-publishing, we can't use sbt to build.

There is a draft for 2.13 support at https://github.com/twitter/scrooge/compare/develop...martijnhoekstra:213?expand=1  but I don't really understand the code so I'm not entirely sure it's correct, even though it's a minimal diff.

In addition, it relies on sbt 2.13.0-RC3 there to (hopefully?) avoid the sbt 1.2.8 issue. A stable sbt version would probably be much preferable. 1.1.4 doesn't work with scala 2.13

**Comment by ayoub-benali** [comment]
> it relies on sbt 2.13.0-RC3 there to (hopefully?) 

You mean sbt `1.3.0-RC3` ?

I don't see a problem kicking off a PR with sbt `1.3.0-RC3` by the time we are about to merge it we either upgrade sbt or make an other PR later.

So far we are still blocked by https://github.com/twitter/util/issues/253

**Comment by martijnhoekstra** [comment]
Right, `1.3.0-RC3`

Is it possible to coerce both in at the same time? It would be a shame if we had to wait for a 19.9 release of twitter util, and then miss the 19.9 release for scrooge, and have to bring it along with 19.10 if my branch is indeed sufficient.

**Comment by ayoub-benali** [comment]
> Is it possible to coerce both in at the same time

Unless there is a valid reason to stick to sbt `1.1.4` we should push for an update. 

The release schedule you describe is very bad :/ 
Do all these lib need to be released at the exact same time ? Otherwise we might be able to release them all in the same month just with few hours/days of difference

**Comment by martijnhoekstra** [comment]
Yeah, that's what I was asking about: is it possible to get both scrooge and util updated in the same release cycle.

**Comment by ayoub-benali** [comment]
> Yeah, that's what I was asking about: is it possible to get both scrooge and util updated in the same release cycle.

@yufangong can you or other maintainers help with this ?

**Comment by SethTisue** [comment]
twitter-util has now been published for 2.13

**Comment by ayoub-benali** [comment]
I think this issue can be closed as a 2.13 release is available on maven 
https://mvnrepository.com/artifact/com.twitter/scrooge-serializer_2.13/19.9.0

**Comment by martijnhoekstra** [comment]
I'd argue against closing until the last (test!) subprojects are also on 2.13

That depends on finagle-thriftmux, which for which a PR is open in that repo.
