### ISSUE TITLE
Support i8 type

### ISSUE THREAD

**Issue by knight76** [twitter/scrooge#309]
Support for I8

### Expected behavior
According to https://thrift.apache.org/docs/idl, thrift support i8.

[26] BaseType        ::=  'bool' | 'byte' | 'i8' | 'i16' | 'i32' | 'i64' | 'double' | 'string' | 'binary' | 'slist'

### Actual behavior
When I compiled i8 field using sbt scrooge 19.5.1, below exception is thrown.

[error] Caused by: com.twitter.scrooge.frontend.TypeNotFoundException: i8
[error]   8: required i8 score;
[error]               ^
[error] 	at com.twitter.scrooge.frontend.TypeResolver.$anonfun$resolveFieldType$2(TypeResolver.scala:143)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at com.twitter.scrooge.frontend.TypeResolver.resolveFieldType(TypeResolver.scala:143)
[error] 	at com.twitter.scrooge.frontend.TypeResolver.apply(TypeResolver.scala:307)
[error] 	at com.twitter.scrooge.frontend.TypeResolver.apply(TypeResolver.scala:294)
[error] 	at com.twitter.scrooge.frontend.TypeResolver.$anonfun$apply$3(TypeResolver.scala:259)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

**Comment by kevinoliver** [comment]
Thanks for letting us know. Would love a patch if you or anyone else is up for it.

**Comment by yufangong** [comment]
Thanks for reporting @knight76, this is fixed by https://github.com/twitter/scrooge/pull/313, and merged https://github.com/twitter/scrooge/commit/03d84aea40c9edf87e8c69090c5077b8779fa655.
