### ISSUE TITLE
Can 'passthrough_fields' be a private field if wanted when Scrooge generates codes (sbt plugin)?

### ISSUE THREAD

**Issue by cosmir17** [twitter/scrooge#312]
Is there a way to make 'passthrough_fields' as a private field when the code is generated.
I am using `scrooge-sbt-plugin' addSbtPlugin("com.twitter" % "scrooge-sbt-plugin" % "19.5.1")`

### Expected behavior
I want to see scala files(objects) generated, with 'passthrough_fields' as a private field. If it's a private field and there are methods handling this field indirectly, It would be excluded in the json serialisation process.

### Actual behavior
'passthrough_fields' is exposed as a public field in generated objects so that it also gets added to json serialization process automatically.

### Steps to reproduce the behavior
I am using the following dependencies in my 'build.sbt' script. 
```
"org.apache.thrift" % "libthrift"     
"com.twitter"       %% "scrooge-core"  "libthrift"),
"com.twitter"       %% "finagle-thrift" 
```
I also use scrooge sbt plugin in 'plugins.sbt' file inside project folder.
`addSbtPlugin("com.twitter" % "scrooge-sbt-plugin" % "19.5.1")`

I then run 'sbt clean compile' command to generate object from Thrift files.

Generated objects contains 'passthrough_fields' as a public field and it gets included in json serialization process (I am using Finagle & json4s-jackson).*

I am not suggesting for 'passthroughFields' to be removed.

**Comment by mosesn** [comment]
as @enbnt mentioned in https://github.com/twitter/finagle/issues/776 I think you should use a different domain object for serializing it with json4s-jackson.  Scrooge's generated structs aren't intended to be used this way, so I think you'll have better results with that approach.
