### ISSUE TITLE
twitter.github.io/scrooge is missing

### ISSUE THREAD

**Issue by ekohlwey-fb** [twitter/scrooge#332]
The `gh-pages` branch of Scrooge's repo is missing.

### Expected behavior

You can go to `twitter.github.io/scrooge` and see docs.

### Actual behavior

You get a 404.

### Steps to reproduce the behavior

Use a browser to navigate to `twitter.github.io/scrooge`.

**Comment by ryanoneill** [comment]
Hi @ekohlwey-fb, thanks for reporting. We are in the process of publishing the 20.6.0 release. We've recently migrated everything to GitHub Actions, and there are still a few issues to work out. We are actively working on it and this should be entirely resolved within the next few hours. Thanks.

**Comment by ryanoneill** [comment]
This should be fixed now @ekohlwey-fb.
