### ISSUE TITLE
scrooge-generator: Update Apache Thrift `Processor.process` signature

### ISSUE THREAD

**Issue by Marcono1234** [twitter/scrooge#351]
**Describe the bug**
Starting with Apache Thrift 0.13.0 released in 2019, the return type of `Processor.process` was changed from `boolean` to `void` (see https://github.com/apache/thrift/pull/1678).
This prevents using these Thrift versions with the code generated by scrooge-generator because it still uses `boolean` as return type:
https://github.com/twitter/scrooge/blob/082b11ee840e0a75a421ac6bf97a441618bc459b/scrooge-generator/src/main/resources/apachejavagen/service.mustache#L386

**To Reproduce**
1. Use scrooge-generator with ' java' as target language
2. Compile with Apache Thrift >= 0.13.0 as dependency

**Expected behavior**
Code generated by scrooge-generator should be compatible with the latest Apache Thrift versions.

**Comment by jyanJing** [comment]
Hi @Marcono1234, thanks for reaching out to us! Our internal version for Apache Thrift is 0.10.0, upgrading the version to 0.13.0 will be a big effort especially given the breaking changes in the new API, so far I am not aware we have plans for the upgrade. Would you be able to work with Apache Thrift 0.10.0?

**Comment by Marcono1234** [comment]
Thanks for the fast response!
I mainly wanted to point this out in case you were not aware of these changes to the Thrift API. It is not blocking me.
Feel free to close this issue if you don't plan to upgrade the Thrift version used internally by you any time soon.

Edit: But maybe it would be good to mention this recommended Thrift version in the documentation. I did not notice it being mentioned anywhere. https://twitter.github.io/scrooge/CodeGenDep.html might be a good place to mention it.

**Comment by jyanJing** [comment]
Thank you for raising this issue to us, it is great to hear that you are not blocked, let's keep this open so it is on our radar!
Re: documentation, good point, I will have a patch to mention the version in the doc.

**Comment by jyanJing** [comment]
[Added](https://github.com/twitter/scrooge/commit/b6251a8dc075bcd32bfda8ab4d8bfa3ebbce61c1) some documentation to Scrooge doc, Github should be able to update the doc soon. thank you again for your suggestion!

**Comment by mosesn** [comment]
Thanks, we've updated the documentation!  https://twitter.github.io/scrooge/CodeGenDep.html  We're going to close this ticket for now, but it's still on our radar to upgrade the version of Thrift that we're targeting in the future.
