### ISSUE TITLE
The variables in the startup script should be changed to the approprivate value by the deploy process.

### ISSUE THREAD

**Issue by jackliuooooooo** [twitter/scrooge#76]
I find the file named scrooge at "${PROJECT_HOME}/scrooge-generator/src/scripts", and here are the contents :

#!/bin/bash
HERE=$(dirname $(readlink $0 || echo $0))
java -jar $HERE/../scrooge-@VERSION@.jar "$@"

The variables, such as @VERSION@ should be changed by the deploy process.

**Comment by mosesn** [comment]
This file no longer exists, so I think we're good.  It was changed to https://github.com/twitter/scrooge/blob/develop/bin/run which I don't think has the same problem.
