### ISSUE TITLE
Provide some configuration around the collection types used.

### ISSUE THREAD

**Issue by seanparsons** [twitter/scrooge#77]
It's often preferable to specify that the types generated are definitely immutable (scala.collection.immutable.Map rather than scala.collection.Map for example), especially when using libraries like scalaz. A config option to specify that would make this easier, as from looking at the code I can't see anything that requires mutability.

**Comment by mosesn** [comment]
We're probably not going to add this feature, so I'm going to close this issue.  Most of the data structures are immutable under the hood, although it will be a larger effort to change the types to be immutable too.
