### ISSUE TITLE
Typedefs from an included thrift are neither imported nor referenced by package

### ISSUE THREAD

**Issue by sodabrew** [twitter/scrooge#8]
Here's an attempt at extracting a minimum repro:

Foo.thrift:

```
package com.example.foo

struct OneFoo
{
  1: i32 foo_id
}

typedef list<OneFoo> ManyFoos
```

Bar.thrift

```
package com.example.bar

include "foo.thrift"

// Generates, but FAILS to compile
struct Bar
{
  1: foo.ManyFoos thefoobars
}

// WORKS
struct Bar
{
  1: list<foo.OneFoo> thefoobars
}
```

The problems appears to be that the Scala output in bar.scala is this:

```
class Bar(thefoobars: Seq[OneFoo]) extends ThriftStruct { ... }
```

It should work the typedef backwards and either prefix:

```
class Bar(thefoobars: Seq[foo.OneFoo]) extends ThriftStruct { ... }
```

Or it should import foo._ into bar.scala (there is as include "foo.thrift" in "bar.thrift", so I think it makes sense to generate a corresponding import).

**Comment by mosesn** [comment]
Looks like this works now.  Test here: https://github.com/twitter/scrooge/blob/develop/scrooge-generator-tests/src/test/thrift/scala/inheritance/ddd.thrift
