### ISSUE TITLE
turn off camel casing

### ISSUE THREAD

**Issue by johnrfrank** [twitter/scrooge#86]
We just started using Scrooge for this example of streamcorpus generation in Scala, and it seems to be converting all of our method names to camel case.  For example,  "entity_type" becomes "entityType"

https://github.com/trec-kba/streamcorpus/blob/v0.3.0-dev/if/streamcorpus-v0_3_0.thrift

Is there a reason for this?  At the very least, it invalidates our documentation.  It also makes it painful to port code from other languages that use these thrift interfaces.

https://github.com/trec-kba/streamcorpus/blob/v0.3.0-dev/examples/scala/streamcorpus_example/AddTagging.scala

Can we turn off this camel casing behavior?

**Comment by dmontauk** [comment]
This is turning out to be a problem for us as well. We're happy to do it locally-only; any chance we could get a link to the class we need to override to get rid of this behavior?

**Comment by kevinoliver** [comment]
@dmontauk — I *think* a good place to start would be ``Identifier.toCamelCase``
