### ISSUE TITLE
hashCode() for objects with optional fields throws IllegalArgumentException

### ISSUE THREAD

**Issue by eshelestovich** [twitter/scrooge#94]
Scrooge generates an incorrect `hashCode()` implementation for Java objects with optional fields causing `IllegalArgumentException`.

Steps to reproduce:
- Create a new Thrift structure:

```
struct TestStruct {
    1: required string key;
    2: optional binary value;
}
```
- Generate Java source.
- Create an instance of `TestStruct` class. Do not set value. 
- Call `hashCode()` directly or put the object into a `j.u.HashMap`:

``` java
final TestStruct obj = new TestStruct.Builder().key("key1").build();
new HashMap<Event, String>().put(event, "test");
```

Expected result: successfully calculated hash code.
Actual result:

```
java.lang.IllegalArgumentException
    at com.twitter.scrooge.Option$1.get(Option.java:23)
    at com.twitter.scrooge.Option$1.get(Option.java:21)
    at com.test.TestStruct.hashCode(TestStruct.java:100)
```

Fix #95

**Comment by kevinoliver** [comment]
I believe this was for the experimental-java generated code which is no longer part of the project.
